doc: fix esplora's docker image name in README
Blockstream/esplora pull request #273
Opened 2020-11-10 11:21 UTC by harshjv

Esplora's docker image is available at `blockstream/esplora`

2020-11-10 11:37 UTC, shesek commented
These `docker run` instructions refer to the [`docker build` instruction](https://github.com/Blockstream/esplora/blob/master/README.md#how-to-build-the-docker-image) above them, which would build this as an image named `esplora`.

Perhaps you could instead add a sentence under the *"How to build the Docker image"* section, saying something like "You can also use the pre-build image at `blockstream/esplora` instead of building it locally"?.

2021-04-20 16:09 UTC, wj42420 approved these changes

2021-04-20 16:13 UTC, wj42420 requested changes

2021-04-20 16:13 UTC, wj42420 commented on README.md
>  docker run -p 50001:50001 -p 8080:80 \
Good

2024-10-16 23:13 UTC, philippem commented
The docker image in the README refers to the image as built locally (using the instructions higher up in the README).

2024-10-16 23:13 UTC, closed without merging